---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: infra
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://codecentric.github.io/helm-charts
      chart: keycloak
      version: 10.3.0
      sourceRef:
        kind: HelmRepository
        name: codecentric
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: alemairebe/keycloak
      tag: 12.0.4
    # extraEnvFrom: |
    #   - secretRef:
    #       name: 'keycloak-env-values'
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      rules:
        - host: keycloak.kube.com
          paths:
            - /
    postgresql:
      enabled: false
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: true
