---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: infra
spec:
  interval: 5m
  releaseName: keycloak
  chart:
    spec:
      chart: keycloak
      version: "10.3.x"
      sourceRef:
        kind: HelmRepository
        name: codecentric
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: quay.io/keycloak/keycloak
      tag: "12.0.4"
