---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: infra
spec:
  interval: 5m
  releaseName: metallb
  chart:
    spec:
      chart: metallb
      version: 4.1.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
  # install:
  #   remediation: # perform remediation when helm upgrade fails
  #     retries: 3
  # upgrade:
  #   remediation: # perform remediation when upgrade fails
  #     retries: 3
  #     cleanupOnFail: true
  values:
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 192.168.1.240/28
    controller:
      image:
        registry: docker.io
        repository: metallb/controller
        tag: v0.9.6
    speaker:
      image:
        registry: docker.io
        repository: metallb/speaker
        tag: v0.9.6
