---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: infra
spec:
  interval: 5m
  chart:
    spec:
      chart: metrics-server
      version: "5.8.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
  values:
    ingress:
      hosts:
        - dash.kube.com
