---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: infra
spec:
  interval: 5m
  chart:
    spec:
      chart: metrics-server
      version: "5.8.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
  values:
    # image:
    #   registry: docker.io
    #   repository: rancher/metrics-server
    #   tag: v0.4.1
    apiService:
      create: true
