# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: metrics-server
#   namespace: infra
# spec:
#   interval: 5m
#   chart:
#     spec:
#       chart: metrics-server
#       version: 2.11.4
#       sourceRef:
#         kind: HelmRepository
#         name: helm-stable
#         namespace: flux-system
#       interval: 10m
#   values:
#     image:
#       repository: gcr.io/google_containers/metrics-server-arm64
#       tag: v0.3.6
#     args:
#       - --kubelet-insecure-tls=true
#       - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
