---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: infra
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: 3.25.0
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: flux-system
      interval: 1m
  values:
      service:
        type: LoadBalancer
        # loadBalancerIP: 192.168.2.240
        loadBalancerSourceRanges:
          - 192.168.2.240/28
        externalTrafficPolicy: Local
