---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.influxdata.com/
      chart: influxdb
      version: 4.9.14
      sourceRef:
        kind: HelmRepository
        name: influx-data
        namespace: flux-system
      interval: 10m
  values:
    persistence:
      storageClass: local-path
      size: 10Gi
    config:
      opentsdb:
        enabled: true
