---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  interval: 10m
  url: https://rancher.github.io/local-path-provisioner/
  timeout: 3m