---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: system
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: "0.9.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
  values:
      existingConfigMap: system/metallb-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metallb-config
  namespace: system
data:
  config: |
    address-pools:
    - name: kube-address-pool
      protocol: layer2
      addresses:
      - 192.168.2.240/28
