---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: system
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: 2.3.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
  test:
    enable: false # helm tests
  install:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
  upgrade:
    remediation: # perform remediation when upgrade fails
      retries: 3
      cleanupOnFail: true
  values:
    controller:
      image:
        repository: metallb/controller
        tag: v0.9.6
    speaker:
      image:
        repository: metallb/speaker
        tag: v0.9.6
    configInline:
      address-pools:
        - name: default
          protocol: layer2
          addresses: 192.168.2.240-192.168.2.256
